### ISSUE TITLE
Score and game reset logic

### ISSUE THREAD

**Issue by labrose** [brosela/.github#1]
## Overview

We want players of OctoArcade Invaders to find satisfaction from beating each other's high scores. In the pursuit of high scores, some gamers will want to reset the level midway to try again when they know they made a mistake.

## Tasks
_Brainstorm during our next Game Loop 🎢  sync_

- [ ] Implement score calculation system
- [ ] Add level reset option to pause menu
- [ ] Add weighting to score calculation based on usage of cannon vs beam
- [ ] Adjust point totals for defeating different alien types

**Comment by drewbaumann** [comment]
@labrose The game looked interesting so I just had to try and hunt it down. The new Issues looks awesome (from the marketing page) and I have been anxiously waiting for it since I heard rumors of it. Nice work!

PS: Sorry for intruding on your testing org 😅

**Comment by labrose** [comment]
Ha! You found my screenshot issue 😄 

Sadly the game does not really exist, but would be super cool if it did. Maybe for the next game-off? 😉
